### PR TITLE
Re-import CIRCL

### LINKED ISSUE #113: Update CIRCL reference

### PR DESCRIPTION
**Pull request by chris-wood**
Closes #113.

This updates the CIRCL code to pull in latest changes, including those in the kem/hybrid package.

### CODE REVIEW

**Comment by chris-wood** [comment]
@Lekensteyn the tests are failing, so maybe this isn't as simple as just running `python3 cf-copy-from-circle.py`?

**Comment by Lekensteyn** [comment]
There are some new dependencies. If we don't need them, then the script needs to be updated to strip them.
```
 /home/runner/work/go/go/src/circl/xof/xof.go:13:2: no required module provides package golang.org/x/crypto/blake2b; to add it:
	go get golang.org/x/crypto/blake2b
/home/runner/work/go/go/src/circl/xof/xof.go:14:2: no required module provides package golang.org/x/crypto/blake2s; to add it:
	go get golang.org/x/crypto/blake2s
/home/runner/work/go/go/src/circl/group/ristretto255.go:10:2: no required module provides package github.com/bwesterb/go-ristretto; to add it:
	go get github.com/bwesterb/go-ristretto
```

@bwesterb @armfazh Do you have some cycles to fix up the import script?

**Comment by chris-wood** [comment]
I removed the two offending files from the list of things imported, and changed the update script to pull from `main` instead of `master.`

**Comment by armfazh** [comment]
Look at #115

**Pull request closed without merging**
