### PR TITLE
Add insecure verify #62

### PR DESCRIPTION
**Pull request by claucece**
Adding to allow usage of mock certs for testing.

cc./ @armfazh

### CODE REVIEW

**Comment by armfazh** [comment]
what is the effect in DCs when this flags is enabled?
in the tests, we want that the verification of DCs be tested too.

**Comment by claucece** [comment]
> what is the effect in DCs when this flags is enabled?

Verifies the root and the chain. So you will have to provide the cert chain.

> in the tests, we want that the verification of DCs be tested too.

why would you want it if you are testing with a mock certificate?


EDIT: DC are only placed on the leaf (end-entity) certificate: this means that only the leaf and the DC have to be valid for testing purposes. The verification of the whole certificate chain is already tested in other parts of crypto/tls.

**Comment by armfazh** [comment]
> EDIT: DC are only placed on the leaf (end-entity) certificate: this means that only the leaf and the DC have to be valid for testing purposes. The verification of the whole certificate chain is already tested in other parts of crypto/tls.

Thanks for clarifying this to me.

**Review by armfazh — APPROVED** [review]

**Comment by Lekensteyn** [comment]
> why would you want it if you are testing with a mock certificate?

It is more realistic, perhaps the implementation treats InsecureSkipVerify specially and skips DC validation too. However given that your tests already seem to cover negative cases too for DC, it probably doesn't matter. Thanks for the clarification!

**Review by Lekensteyn — APPROVED** [review]

**Comment by claucece** [comment]
> It is more realistic, perhaps the implementation treats InsecureSkipVerify specially and skips DC validation too. However given that your tests already seem to cover negative cases too for DC, it probably doesn't matter. Thanks for the clarification!

Yes! We have some lengthy debate around InsecureSkipVerify skipping the verification for a DC too: as it is even with InsecureSkipVerify set to true, the DC will always be validated.

**Pull request merged**
