### PR TITLE
nits following 1.20.1 rebase

### PR DESCRIPTION
**Pull request by cjpatton**
*   crypto/tls: Panic on unhandled curve ID

    As of go 1.20.1 the curveIDForCurve() method returns a flag indicating
    whether the the curve was known. An unknown curve is usually handled
    with a panic(), since this condition indicates a programmer error.
    However, the key exchange code we've added is silent.

    For consistency, ensure the caller always panics if curveIDForCurve()
    indicates the curve was unknown.

*   crypto/tls: Make ECH acceptance confirmation more explicit

    Replace the variable names involved in deriving the acceptance
    confirmation tag with more explicit names.

### CODE REVIEW

**Comment by bwesterb** [comment]
Thanks for the review, Chris! Not checking return of `curveIDForCurve` is sloppy, but won't break anything. Maybe we get some weird metrics. I want to propose to roll these changes into the next rebase.

**Comment by cjpatton** [comment]
Agreed, no need to block on this!

**Comment by bwesterb** [comment]
See #140

**Comment by cjpatton** [comment]
> See #140

This reference is for the 1.20.1 rebase. What exactly do you want me to look at?

**Comment by bwesterb** [comment]
> > See #140
> 
> This reference is for the 1.20.1 rebase. What exactly do you want me to look at?

That half  these changes got incorporated into that rebase.

**Comment by bwesterb** [comment]
(I forgot to close.)

**Comment by cjpatton** [comment]
Oh I see you meant to add these in the top comment of https://github.com/cloudflare/go/pull/144.

**Pull request closed without merging**
