### PR TITLE
Normal vendor, restructure and add P256Kyber768Draft00

### PR DESCRIPTION
**Pull request by bwesterb**
Several changes to align this fork closer to some of our other Go forks.

1. Vendor CIRCL in the normal way, instead of copying under a `circl` package and update to `main`.
2. Merge three PQ signatures commits into one.
3. Adds P256Kyber768Draft00 key agreement.
5. Left-over nits of @cjpatton  from 1.20.1 rebase

To generate range diff, use `git range-diff go1.20.1..cf/cf go1.20.1..cf/bas/restructure`. It's too long to be pasted.

### CODE REVIEW

**Comment by Lekensteyn** [comment]
Reviewed, LGTM. Informative notes from review:

> Vendor CIRCL in the normal way, instead of copying under a circl package and update to main.

This also updates [x/crypto](https://github.com/golang/crypto/compare/2c476679df9a...v0.6.0), [x/net](https://github.com/golang/net/compare/1e63c2f08a10...v0.6.0), and indirectly x/sys and x/text. The changes to the first two libraries do not seem too interesting though (I did not check the latter two):
```diff
@@ -3,11 +3,12 @@ module std
 go 1.20

 require (
-       golang.org/x/crypto v0.3.1-0.20221117191849-2c476679df9a
-       golang.org/x/net v0.3.1-0.20221206200815-1e63c2f08a10
+       github.com/cloudflare/circl v1.3.3-0.20230227211051-c2daa9563cc7
+       golang.org/x/crypto v0.6.0
+       golang.org/x/net v0.6.0
 )

 require (
-       golang.org/x/sys v0.3.0 // indirect
-       golang.org/x/text v0.5.0 // indirect
+       golang.org/x/sys v0.5.0 // indirect
+       golang.org/x/text v0.7.0 // indirect
 )
```

For some reason the `github.com/bwesterb/go-ristretto` dependency got also dropped.

Commit `cmd/api, go/build: ignore CF-specific API changes` got partially split into `go/build: don't check dependencies of vendored circl library`, so if you were going to make any changes, I would drop `go/build` from the first commit message.

> Merge three PQ signatures commits into one.

LGTM, squashes a fix and a new option into one commit. Given that vendoring is in use, a merge conflict should be easier to resolve than before.

> Adds P256Kyber768Draft00 key agreement.

Ack. This `P256Kyber768Draft00` (0xfe32) kex is on top of the existing `X25519Kyber512Draft00` (0xfe30) and `X25519Kyber768Draft00` (0xfe31) support.

> Left-over nits of @cjpatton from 1.20.1 rebase

Ack.

To make my life as a reviewer easier, I started with comparing the outputs of these and compared individual commits in two tabs if needed:
```
git range-diff go1.20.1..gh/cf go1.20.1..gh/bas/restructure -- ':!src/vendor' ':!src/circl'
git diff --stat -p --color-words gh/cf gh/bas/restructure -- ':!src/circl' ':!src/vendor/github.com/cloudflare/circl'
```

PS.
It is funny how `cf-copy-from-circle.py` begins with `#` **Temporary file** `: copies Dilithium from Cloudflare's circl library into crypto.`

**Review by Lekensteyn — APPROVED** [review]
LGTM. For informative notes, see my comment on the PR.

**Comment by Lekensteyn** [comment]
Oops, the x/sys bump might have broken one test:
```
--- FAIL: TestDependencyVersionsConsistent (0.16s)
    moddeps_test.go:407: Modules within GOROOT require different versions of golang.org/x/sys.
    moddeps_test.go:419: cmd	requires v0.3.0
    moddeps_test.go:419: std	requires v0.5.0
```

**Comment by bwesterb** [comment]
Yeah, for some reason I didn't hit it before. Fixing it now...

**Comment by bwesterb** [comment]
@Lekensteyn https://github.com/cloudflare/go/pull/145

**Pull request merged**
