### PR TITLE
crypto/tls: Fix the testingTriggerHRR condition

### PR DESCRIPTION
**Pull request by cjpatton**
The server sends an HRR if the client does not offer a key share for a key exchange algorithm the server doesn't support. For  testing purposes, it's useful to trigger this codepath manually. If testingTriggerHRR in common.go is set, then the server only advertises support for algorithms that the client supports, but did not provide a key share for.

This change fixes a bug in the trigger logic. It seemed to work for the existing algorithm preferences, but could break if the  preferences change.

cc/ @chris-wood

### CODE REVIEW

**Review by claucece — APPROVED** [review]

**Comment by claucece** [comment]
Should we merge @cjpatton ?

**Comment by chris-wood** [comment]
Good catch. Out of curiosity, what are the groups the client sends in "supported_groups" but does not send a corresponding key share?

**Review by chris-wood — APPROVED** [review]

**Comment by cjpatton** [comment]
> Good catch. Out of curiosity, what are the groups the client sends in "supported_groups" but does not send a corresponding key share?

Quite a lot! E.g., P521.

 I'm pretty sure it only sends X25519, though KEM TLS might change this?

**Comment by chris-wood** [comment]
Yeah, it will. I wasn't sure what the supported groups were for Go's implementation. Thanks!

**Pull request merged**
